### ISSUE TITLE
code of Figure 4. t-SNE

### ISSUE THREAD

**Issue by dana-niu** [Gahyeonkim09/AAPL#2]
hello
Can you provide the relevant code of Figure 4. t-SNE visualization for learning?
Sincerely look forward to your reply.

**Comment by Gahyeonkim09** [comment]
Hello, thanks for your attention.
If you use the "TSNE" method in [trainers/AAPL_visualize.py](https://github.com/Gahyeonkim09/AAPL/blob/main/trainers/AAPL_visualize.py), you should be able to obtain the t-SNE plot shown in Figure 4. If you have any additional questions, please feel free to ask.

**Comment by dana-niu** [comment]
Thank you very much for your reply.
Your reply was very helpful.
I will try and learn.
