### ISSUE TITLE
A question about result

### ISSUE THREAD

**Issue by Sandy-program** [Gahyeonkim09/AAPL#3]
Hello author, I found that the results of AAPL in Table 1 are not consistent with the average results of AAPL in Table 2, but the indicators of the methods you listed for comparison in the two tables are consistent. Why is that?
Sincerely look forward to your reply.
![image](https://github.com/user-attachments/assets/3803cca7-12f1-4ab8-a8c2-8bfcc48ef1b8)
![image](https://github.com/user-attachments/assets/f989fcb3-bda1-4bd1-8d59-36359ef039ed)

**Comment by Gahyeonkim09** [comment]
Hello Sandy,

Apologies for the delayed response.
To answer your question, Table 1 compares AAPL and CoCoOp with augmentation, showing the results of experiments designed to evaluate the impact of the ad triplet loss. In these experiments, the scaling parameters for CE loss and ad triplet loss (alpha and beta) were both set to 1.

For the accuracy results in Table 2, from the base-to-new generalization experiment, these were obtained by tuning the scaling parameters alpha and beta for CE loss and ad triplet loss, as explained in Section 4.2.

Thank you!
